apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - deployment.yml
  - service.yml
  - ingress-unified.yml

labels:
  - pairs:
      app.kubernetes.io/name: mimoq-webapp
      app.kubernetes.io/version: "1.0.0"
