apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - postgres-secret.yml
  - postgres-deployment.yml
  - migration-job.yml
  - service-account.yml
  - pvc-test-result.yml
  - deployment.yml
  - service-server.yml

labels:
  - pairs:
      app.kubernetes.io/name: mimoq-server
      app.kubernetes.io/version: "1.0.0"
